In [1]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
import re

In [3]:
page=requests.get("https://www.icc-cricket.com/rankings/mens/player-rankings/odi/bowling")
page

In [4]:
soup=BeautifulSoup(page.text,'lxml')

In [5]:
table_body=soup.find('table')
row_data=[]

In [6]:
for row in table_body.find_all('tr'):
    col=row.find_all('td')
    col=[ele.text.strip()for ele in col]
    row_data.append(col)
df=pd.DataFrame(row_data)
df

,0,1,2,3,4
0,None,None,None,None,None
1,1\n \n\n\n(0),Trent Boult,NZ,726,"770 v West Indies, 22/06/2019"
2,2\n \n\n\n(0),Chris Woakes,ENG,700,"711 v Sri Lanka, 04/07/2021"
3,3\n \n\n\n(0),Josh Hazlewood,AUS,698,"733 v England, 26/01/2018"
4,4\n \n\n\n(0),Matt Henry,NZ,683,"691 v Bangladesh, 26/03/2021"
...,...,...,...,...,...
96,96\n \n\n\n(0),Junaid Siddique,UAE,372,"372 v Nepal, 21/03/2022"
97,97\n \n\n\n(0),Norman Vanua,PNG,366,"366 v Nepal, 26/03/2022"
98,98\n \n\n\n(0),Mohammad Nawaz,PAK,365,"376 v South Africa, 07/04/2021"
99,99\n \n\n\n(0),Jeffrey Vandersay,SL,365,"365 v Zimbabwe, 21/01/2022"
100,100\n \n\n\n(0),Lakshan Sandakan,SL,365,"383 v Bangladesh, 25/05/2021"

In [8]:
header=[]
for i in soup.find_all("th"):
    col_name=i.text.strip().lower().replace(" ","_")
    header.append(col_name)
results=pd.DataFrame(row_data,columns = header)
results

,pos,player,team,rating,career_best_rating
0,None,None,None,None,None
1,1\n \n\n\n(0),Trent Boult,NZ,726,"770 v West Indies, 22/06/2019"
2,2\n \n\n\n(0),Chris Woakes,ENG,700,"711 v Sri Lanka, 04/07/2021"
3,3\n \n\n\n(0),Josh Hazlewood,AUS,698,"733 v England, 26/01/2018"
4,4\n \n\n\n(0),Matt Henry,NZ,683,"691 v Bangladesh, 26/03/2021"
...,...,...,...,...,...
96,96\n \n\n\n(0),Junaid Siddique,UAE,372,"372 v Nepal, 21/03/2022"
97,97\n \n\n\n(0),Norman Vanua,PNG,366,"366 v Nepal, 26/03/2022"
98,98\n \n\n\n(0),Mohammad Nawaz,PAK,365,"376 v South Africa, 07/04/2021"
99,99\n \n\n\n(0),Jeffrey Vandersay,SL,365,"365 v Zimbabwe, 21/01/2022"
100,100\n \n\n\n(0),Lakshan Sandakan,SL,365,"383 v Bangladesh, 25/05/2021"